# Generated by Django 6.0.5 on 2026-05-26 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoproject', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='infectedmachine',
            name='ip',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
