# Generated by Django 6.0.5 on 2026-05-26 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djangoproject', '0002_infectedmachine_ip'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='finished',
        ),
    ]
