# Generated by Django 6.0.5 on 2026-05-26 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoproject', '0003_remove_job_finished'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='started_at',
            field=models.DateTimeField(null=True),
        ),
    ]
