# Generated by Django 6.0.5 on 2026-06-06 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoproject', '0004_job_started_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='infectedmachine',
            name='job_ask_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='job',
            name='chunks_received_count',
            field=models.IntegerField(default=0),
        ),
    ]
