# Generated by Django 6.0.5 on 2026-06-07 10:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoproject', '0005_infectedmachine_job_ask_count_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobEndQueue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('processable_at', models.DateTimeField()),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='djangoproject.job')),
            ],
        ),
    ]
